create table
  public.cart (
    cart_id integer generated by default as identity,
    created_at timestamp without time zone not null default (now() at time zone 'utc'::text),
    customer_name text not null,
    constraint cart_pkey primary key (cart_id),
    constraint cart_cart_id_key unique (cart_id)
  ) tablespace pg_default;

create table
  public.global_inventory (
    id serial,
    num_red_potions integer not null,
    num_red_ml integer not null,
    gold integer not null,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.item_sku (
    item_sku text not null,
    red_ml smallint not null default '0'::smallint,
    green_ml smallint not null default '0'::smallint,
    blue_ml smallint not null default '0'::smallint,
    dark_ml smallint not null default '0'::smallint,
    price integer not null default 0,
    constraint item_sku_pkey primary key (item_sku)
  ) tablespace pg_default;

create table
  public.cart_content (
    cart_id integer not null,
    created_at timestamp without time zone not null default (now() at time zone 'utc'::text),
    updated_at timestamp without time zone not null default (now() at time zone 'utc'::text),
    item_sku text not null,
    line_item_total integer not null,
    id integer generated by default as identity,
    constraint cart_content_pkey primary key (id),
    constraint cart_content_id_key unique (id),
    constraint cart_content_cart_id_fkey foreign key (cart_id) references cart (cart_id) on update cascade on delete cascade,
    constraint cart_content_item_sku_fkey foreign key (item_sku) references item_sku (item_sku) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.transaction_history (
    id bigint generated by default as identity,
    created_at timestamp without time zone not null default (now() at time zone 'utc'::text),
    description text not null,
    constraint transaction_history_pkey primary key (id),
    constraint transaction_history_id_key unique (id)
  ) tablespace pg_default;

create table
  public.transaction_ledger (
    id bigint generated by default as identity,
    item_sku text null,
    quantity_change integer not null,
    gold_change integer not null,
    transaction_id bigint null,
    constraint transaction_ledger_pkey primary key (id),
    constraint transaction_ledger_item_sku_fkey foreign key (item_sku) references item_sku (item_sku) on update restrict on delete restrict,
    constraint transaction_ledger_transaction_id_fkey foreign key (transaction_id) references transaction_history (id) on update cascade on delete cascade
  ) tablespace pg_default;